Enable installation of test programs

diff --git a/testsuite/netcdf-build-job.yml b/testsuite/netcdf-build-job.yml
--- a/testsuite/netcdf-build-job.yml
+++ b/testsuite/netcdf-build-job.yml
@@ -53,10 +53,14 @@ netcdf-c-build-job:       # This job runs in the build stage, which runs first.
         fi
       - |
         if ! test -d ${NC_C_BUILD_DIR}; then
-          git clone -b main https://github.com/Unidata/netcdf-c.git ${NC_C_BUILD_DIR}
+          git clone -b ${NETCDF_C_BRANCH} ${NETCDF_C_REPOSITORY} ${NC_C_BUILD_DIR}
         fi
       - cd ${NC_C_BUILD_DIR}
-      - git pull --force
+      - git checkout ${NETCDF_C_BRANCH}
+      - |
+        if ! git pull --force; then
+          echo "warning: git pull failed"
+        fi
       - |
         if ! test -d build_dir; then
           mkdir build_dir
@@ -100,10 +104,14 @@ netcdf-cxx4-build-job:       # This job runs in the build stage, which runs firs
         fi
       - |
         if ! test -d ${NC_CXX4_BUILD_DIR}; then
-          git clone -b master https://github.com/Unidata/netcdf-cxx4.git ${NC_CXX4_BUILD_DIR}
+          git clone -b ${NETCDF_CXX4_BRANCH} ${NETCDF_CXX4_REPOSITORY} ${NC_CXX4_BUILD_DIR}
         fi
       - cd ${NC_CXX4_BUILD_DIR}
-      - git pull --force
+      - git checkout ${NETCDF_CXX4_BRANCH}
+      - |
+        if ! git pull --force; then
+          echo "warning git pull failed"
+        fi
       - |
         if ! test -d build_dir; then
           mkdir build_dir
